name: Tests

on:
  push:
      branches:
        - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        token: ${{secrets.SUBMOD_PAT}}
        submodules: recursive
        fetch-depth: 0 # needed to retrieve most recent tag
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: make install
    - name: Generate gRPC Client
      run: make grpc-client
    - name: Run Tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
